### ISSUE TITLE
FEAT: Suggested features

### ISSUE THREAD

**Issue by ahasverus** [FRBCesab/rcompendium#23]
Checklist for potentiel future development:
- New integrations
    - [x] `renv`
    - [x] `docker` (`rbase`, `rstudio`, `geospatial`, `tidyverse`, etc.)
    - [x] `targets` - **Require more reflexion, maybe a function `new_targets()`**
    - [x] `holepunch` - **The package doesn't seem to be in active development**
    - [x] `binder` - **Not a priority**
- GitHub Actions
    - [x] Update `R-CMD-Check`
    - [x] New GHA: Render `README`
- Fix bugs
    - [x] GitHub account vs. organization
    - [x] Documentation

**Comment by bitbacchus** [comment]
I love your package :-)

Maybe:

5. Integration of [holepunch](https://github.com/karthik/holepunch)

**Comment by ahasverus** [comment]
Thanks @bitbacchus!
I will work on a new version of the package very soon and take a look at Holepunch.
