### ISSUE TITLE
Error in proj_in_proj() on Windows devices

### ISSUE THREAD

**Issue by LPDagallier** [FRBCesab/rcompendium#27]
The functions `new_package` or `new_compendium` will return an error on Windows:
`Error in proj_in_proj() : 
  You have created an 'RStudio Project' inside a folder that is already an 'RStudio Project'.` (although the Rproject is a brand newly created Rproject).
I obtained the same error on 2 different machines on Windows (Windows 10, R 3.4.1, both with CRAN and development versions of Rcompendium) but not on a Linux machine (Ubuntu 18.04).

The problem is in the for loop in `proj_in_proj()` function.
Let's say the newly created project (and present working) directory is _C:/Users/userX/Documents/testproj_, then at the iteration i=1 of the for loop, the value of the object `recursive_path` will be 'C:'. For a reason I couldn't figure out, the function `list.files(recursive_path, pattern = "\\.Rproj$")` will interpret the _path_ 'C:' as the present working directory, and thus will return the name of the current .Rproj file (which we want to avoid because it is our newly created -and empty- Rproject). It seems that the value 'C:' is not interpreted as a _path_ because it is actually not a _path_ but a _disk name_. This also explains why the error do not occur on Linux, because the root folder in Linux will always be a '/' without any disk letter.

Thus, in `proj_in_proj()` function, I propose to change the `recursive_path` object from:
`recursive_path <- paste0(paths[1:i], collapse = .Platform$file.sep)`
to
`recursive_path <- paste0(paste0(paths[1:i], collapse = .Platform$file.sep), .Platform$file.sep)`.
This simply adds a file separator at the end of the recursive path, changing our 'C:' in 'C:/' thereby correctly interpreted as a _path_ (and not as the present working directory). This do not affect the interpretation of the other recursive path (those for the iteration >1 in the loop), as for example _C:/Users/userX/Documents/testproj_ is interpreted similarly to _C:/Users/userX/Documents/testproj_**/** by `list.files()`. I tested this change both on Windows and Linux but not on Mac OS.

Let me know if something is unclear.

**Comment by ahasverus** [comment]
Thank you for finding this bug. In fact, even on Unix system the screening of the root folder (`/`) was not working. But I don't understand why R on Windows considers `C:` as the current folder. This is weird...

I have adapted your suggestion in the `proj_in_proj()` function by adding: `recursive_path <- paste0(recursive_path, .Platform$file.sep)`

You can now use the dev version of `rcompendium`. Note that I have added other features in this version: https://github.com/FRBCesab/rcompendium/blob/main/NEWS.md

I will submit this new version to CRAN this week.

Thank you for improving this package.
